sudo: required
language: java
jdk: oraclejdk10
services:
- docker
cache:
  directories:
  - "$HOME/.m2/repository"
before_install:
- git clone https://sources.byzaneo.com/scm/one/maven.git target
install:
- mvn package -U -B -P prod,coverage --settings target/travis/settings.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u $BYZANEO_USERNAME -p $BYZANEO_PASSWORD repository.byzaneo.com
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=repository.byzaneo.com/sms
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
env:
  global:
    secure: gKL3v8joTXvkxmAU6rMiUbjDokchFmQ3mzJSxVoQPJ2XP7Fia9PDhRzgSzHiv6A7sPEneotQSGcWsa0JS6BBR33xAhKpsouSwQplTuSFD8Mf+Vk/SGhaeevMD79FbtK0LCG0XS+TD1vHMp6ZX3FRDN9Y9Ro4cWX4oVM7x1+o9pdVeJYkcmDGT34YpMDnw1/UrWbLMUGB8qO9wPr+BbhLDez1v/dorf9W4MKMC6yXrXZApKh68bqk+bUXWvth/6dw+PYj4b0w6ZxiPnan+cscf+xJf6LFVlYy8JN5cq6NPGHLKecyRzwIPftHoCnD7y4xgM+yff9ibrObsfLqBnq1cjNudoUxP4Q8SMmyG6qCuLogJoXPXv0lTkp7cBejmnSzGqJCm0E1jtvLKTYppFAmk9Ru1nEtm693uL7wzfqoAvap8UqoW+iZrtpcD9VNJeZHjMdQ4UyUq1M4pZ20fZ8RpLXS0WgLljyMyeHZdyFzHmvxeEbV8rc4wdUNsybeUyeLGsLIfD7+5ZLlg9ZGSlE4Ol6L1VWHg+Yh+ySRQGaG8IimSfBVRvEYpw8HgLX2PchvcUXsA/Ku374nHhdKgHfFQeZYMbs+QEIt4Rz8u+u/pJ0W7r66RHRvFZgkmJ4iIYJtbmE73QqNUfXD1iIQelmPlhcnxwRFbdsUDABgR7Gdolc=
