language: java
jdk: openjdk11
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:
  - secure: Az+EJQy9CvemqbC5WncL6Ez66qKDYJ8zUC7G4Yp+fJt6GwjyLLm+Tm5zrLOgnYwNDagUbngrsG2P1d6cyiJ9sGJreOiOuUw1uPw9VM1uYv2XQMCCzjNQBaoyoX7rZtrso2OM3PjCUwJipHdWmEfn2M6PfyzbxKNf40ZmRZCfv16oqTJ6KO/B9RHk70IpaqErVmP+Mrps3gfs+jzaLLVDcM30z2K+MScHX7iuATqU7zDTRM4dwM8kQ5+eN1lYoK4oPb1MBrlTpO+F38zgPfS3pvo9P24glPxkCzWG1pCcGAvGPGQDfE3Ip3IwyVjD4wirWzNqql7etwc1x9m2KGo5i2KFwZzhuln7isdo0mWbyR3BeFTcBDy3RSoFp15bfMAvD00Mzqm4+44eF9zm/uGOCLEHc/HsLF7kR9T9GZc4RKWPdicwxFIC2i4r+IbmjLpvs4t8S2QH/5AxzP5/nLRWtOUVbUbEDa9ssXC0JuL//d32uvdOjpFLm2As00jA5XGUyJQSzhSsYY5fuCnU4au07qTUB83j5DsO0CH6w9QHVYnSfDTlRCjH3w0OVY37bOXFxnMi6Vu5CyilArG4ggYYVw/qwkEl4xmyEuwCVDAKyHAdO2W+7d//Pp1fhN+UGLilU66KanJdHAjjCGZTjpWwsq6Ya6MP0Qk0LSBdBOCTsfI=
  - secure: d+naKFOi3wgSawqxI4KYQYSh2zqEZrJAInWqhY70h+EByp7HkehX6/zyxCoojXXjK5BzvtttN/xI4GW+yjQtyQASJZpYLUsyOY6bjOLg6zbF0tKBN37ruqoUBUBhhhs00jwBFk5UcqrVpm/Cdzhtzt2352BiqTtzKRnF4qZCfMLo2clgKCvNIguBbvhY0YZTeIKQlfJWP5bTBKEOXXa2wOq7HMuwJVJw6Izr+x739gwBFu7l2AVkO/6NOfo/7Malm2vryB1GM7tBuH2CmXIsL7Cah6YL1lXurz5/P/e3Dv/hNMWzcvkGsSRSM301APO9owqHVVXN1AtmRtt3/eDjxsuiOA4NKRnCNRkACGYkhFnq7qVyymIfHil27jkKUeN8+Av6EJq7Hz2qjYf50JmkdqwQC3W4HAtX+FBeQ8J3skFirwwjYCjpXE/uAUnbnIV7ELzYZ/o3SL/tVd7fH+hDC08GQq42u7XtzjzwTXyLMlRBn6t9Gq8aU5PfFl2WarX+daVEILNyHEms5fF+z5vlKog9khRmlQJLsIjUNpCDtCgcRr+RnSuaq90ZWgeSr0Gvk2Z1rSNo9xzdRSQkyXC3ZDGRHV12Orgm3vDtUwunQ8fevMnTHiRqF7+WP7DRDlUXKbGhJnS3K/3ndoBtCgo4JiU4MF9pmQHfQplo2CoKLdc=
  - secure: tpBNm5PQTRyCI8xpGUePwjRtSveilykJsjfXKfGfzgsU3EduLiXq0+WcazUznSyWuuXaLtRGIDG5Mg3+Z7hrWDuFyrSXp6G0s/wyAux3wrRK5wZNzlOxdhWj+aOgcQ+meXX/Gf/XhtmHKeM6afUUgLhh7OI0pyjmWVqVZ8kY2AkKRuQhdi1JJLeaxW6/PKuEIMtxdeQJcSTPSUnBK9MbJfYJUr+y37Vyi8nZix3F+BA90QO4VNuh3ZMw8ZaOAjYoeDCy4WVek+4YMd/fACFYMXXkLT5FhqCHVUVJcAjraeFw+amz3nitfpca3lpWHbm1ppAE4C19aHBXSNSZZE8AjsWhSPZj7c4TzI5C/aixien1k5Kb7cbUkt0swp8VbX+iQn6UdW72V7Z+YKka5feVUeHf2RlbUHnGARSG4FIrDs/mzSxRmz8HQirWceQnjm8qmjRCwOxu0wOaZVsQ7l5u3wYvj80ANKNXqkGcABxv/oW68ZY3BbQDns+X71vE3SDMqoTv0rPgWXGmGb8Qxea1JqPuIC3nZYZnxI2pbT+ieK6b8jNAuWTlu8x2aHRvLKswFf3nRbNlVFEvOe6Pzhggffa/pFLEs+UX0+fwsJyLRZUkno4hwA0souiGXdjchwWiu+Fk/9ByjpAksZYjfP1CdYGUrclh7Nijmg2BtiP8mmk=
  - secure: iXeQv0Xng3jH2ivPNs7kFeutdb6l4BecD+m14v/FxtxHsbwtsg1ZFcWLMhLs86K2dv8JtiX4gPdjFHcvAcNV5CcTDYedUZ66F/6e40YbExA3KhkFg1yb5sCiHZuIdjwsVrTtEG60llOtIawx9QDh62fpp9MgcQy0HwsN6yNal9liTTboDEe9Rin1pu4sRrGZL1dR6H3BQqFUUqZiEt+eR6tN9CjRSaDhmdtCu5zn+9VfLSFcU2bRnTPv+hFvCkGKyuEwfZO57wedIATVgv2+6kTwrsBsUVAZrd3eV+gOAIx8mBpTcgZkKTzddMNP8vzVYu7/+OZLhw+TgqQ0aFBMGgBEQcvaCBpHHjBSroMmWk6VALsM09dwzw3vg5+QRvtaT6J4L19vdJvGY594tsqGoTddTQuCkJcvuEhZlY1hz0YhxX6x+QFRlpbV74Fe/p9NpAELoiRQI+nujZphmtnvE//3GJL88oU3kHvpz/GC4AIYJKXPmd+oCI+M5JE38Yx1INacrYw6miPsTiIz9mwEKKQypoC04PJlfDK75Kcu6+cNXxZ+TX/qzcMAEJ/IuFkgd7pITBdZXOYHqObUl378VEFQjaIr7XyJmp+i4FM/gHn48/lg8fUgZYtBfGM9UAW+c5hw291autHswFcH6QUYXm9lr1kKvhuTYfDGu9YZUZw=
  - secure: mbmVIf2whnk9DS7Bs5Lrq+sDfn7Cezf2Vpdeiy4zUnBqksN/6OqOoqNtpu7yGfDQQhGkjFRkeOad9hhPEewnknyALQlqhy+1e7ouhTHagnlErFS7ulpR/LJTmSK0pocKSxB6YsvoA+0Y4xfLf1bM4hgD1I3lf8vQZig0yb/LasjMSVK7aoaZWEt0ZDrEAvtnHNhpYCKfBLqTsjIbEYZHf01JWFALz/h6KYqpMGg1i4h8fK85ok3HrEDD9JiTbBYZmkn1XSbcWsp0BU2KnEsSv6khd+ZnsPF2w7AsbBpM2ZQw0WEzZqcxTdj9Km3rY91i4arpHMsX4sFHo3DTfyfP1XX8/QVMAlNdereOITYqmTS9Oon/XkMXDuvwv2EVVlfoIHYdc90DNLeStojOc5FKoZdDsJNiktFm3hJ122v2KVKA7hnJJCkcAs8Jg739eBJmzFsG8xD2nPkcqh2Lu3oWRSh6eetKEwNDWjirk6hFKvO3wjWBvXmfN5eh0pzgG22YNQ4Ahkufg7CVh8JGXHAh5L2giNtO0lvfABpTIGz4l7YdeJY4zSO9LFDkPUOnEPBrm2rBoGsOsqErzUq2p0sv1VsdyoRk3v4PMYCxrEZZRI+zHrCbQtDpVdrTMpCDXmwdn3xu9Ix6Gg/Hds9n/5x1O7rwZY0tyEa+04Rg7+C+PMg=
  - TAG=latest
  - IMAGE_NAME=repository.byzaneo.com/sms
before_install:
- git clone https://sources.byzaneo.com/scm/one/travis.git target
install: true
script:
- mvn package -U -B -P prod,coverage --settings target/maven/settings.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- docker login -u $BYZANEO_USERNAME -p $BYZANEO_PASSWORD repository.byzaneo.com
- docker pull "$IMAGE_NAME" || true
- docker build --pull --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .
- docker images
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:${TAG}"
  on:
    branch: master
notifications:
  webhooks:
    on_success: always
    on_failure: never
    on_start: never
    urls:
      - secure: vb9dDNpSkxESiDTyXJ3fQe+2HYZU6gnaFsol1xVUJ/Qm3CfsCH1EfseSB3zb7wYjP6SoUupLFI0ujhtYW60WbSgpLRiD5CEmntNTml0nqXYQPsBq0XBKWrpiYzoC7s+lMAE/kxH0zstIZKaEu/IUMSXIPfv6g1pA1I5B6WiGlqc6PNc61w68HNj96gOtnjPH/nXDCMwb98EdthmlaeXTTfPdnXSKa+iQBDgUC7Ani0Ofb9emXqXFy3abDtxxKPPqNpgaGkIHwJU55IeTTVGTh24Hj3MpOSkyqJuHQxgw3Pt3kzQfKsQYSQ/ZDjwIL5xqiXs8mFiGoaQoSXX5A2KOTVrFoxwbVQIvXHP+YXGI9Gt66p/sPH3r1UMWTkD3Q8/CrI97b32hwPwNVhLrVqvegiVBOuz8KSLwiu5Gt2I4a0SAKJEam1jnblSltKC4yD5Z4pJh9+vPaWfFmasXj96zBm6CehY1raAv+JgZ9fU6yBZYl5oz6srv2L9Tsp0HJPHNtTBzBAgWKmkEj9foEqozDyn/BSQQziVCLcH/0v5i/so6oAkw6kW4J/mF6mEud5A94k71Qh9YvGpwhY5RFv3wshrKfHFg76BloO1FSDG8UaWx4S5bqZ9JPixYLgxK8JzRdWWk/sEDEnWILfh9n4F5Dez3VRCEic6fHeaXATx87Zk=
