before_install: "git clone https://sources.byzaneo.com/scm/one/maven.git target"
after_script: "mvn compile --settings target/travis/settings.xml"
language: java
# use Java 10
jdk:
- oraclejdk10

install: true

