sudo: required
language: java
jdk: oraclejdk10
services:
- docker
cache:
  directories:
  - "$HOME/.m2/repository"
before_install:
- git clone https://sources.byzaneo.com/scm/one/travis.git target
install:
- mvn package -U -B -P prod,coverage --settings target/maven/settings.xml
after_success:
- bash <(curl -s https://codecov.io/bash)
- docker login -u $BYZANEO_USERNAME -p $BYZANEO_PASSWORD repository.byzaneo.com
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=repository.byzaneo.com/sms
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
env:
  global:
  - secure: rtC35INg7QDSQDWbIHbuYAC8MQhF5UhTZa3CQ8SOCOt8SKV/6d/DNLgFkDWsKHUk6BM01Xofmewe9nZYGglP48OZXrLwISTckZvLb2fMNIIASchJsNjw95vpAXPO3Ud/7cyRQzWqpbm6LxyUgt1z0GV81Ll659u1nRyUTnR6qvz08klpfUAwN51pOHXsLOG9cT3gN55ryR1LfspaBiQNJe40aKyxXCECRWSK0TOjtVEB4rjLPPf0HHWg5e2+a845Lep9H0D1IcOw8qcoNgaQBQuOsCMKKgjnDR8CiROCi7WbcVi64nn80/kRGDy62FPFV3rpxJpAKMSb61ZB3CMKp+JsreAq+HjhzGayUWz1thhZS0KxMxAlPc/mXbIog2nTch0zjThS/3R7H8Tkjz5c66kk+YZ+7ZcTr4pj5/+Jw40QCjfwVP4p/vMPdSI8n+zkCT0L17jMDnZfsRg9pchxLaZMWDVZzLdABHhXStyRv9bAa1xG5bmpN+Dpzv0IKGl5Cpt/Z62f7iLr6+9pdKhK9Pp7LhTH6gYUr9zWUny6PCfa08yZUVbDUx4tCTD/qDIJ1AwtzJiUAikwKJRarqVkL/+yf8pHAdmPCDvwtsOu8sicm1+PYAPYpWurZ5yifyAsaLLFkKLa3wAShdKhJi1qqObT+gBselgSbAsvGxnnZKk=
  - secure: uv03yUdo5wzNtIe42dfCd01XkX5f26v6YslSQncDPQC1+3yQ5ts0l1p1sscqXYdiZwqgiOsriCyEo2OF1rNS6nvsE25Cl3j+4gBKazXmSUj37qbem2kxP1Sod5YAaYVy26GBIE9aXMyzx9By1jivAJZrmrQwlD8TYpRD1tBlrmRHwBttArxXZu0+onlv0s1aLo/nIRxhL9Vfk3mbgCSfyiMlLZ+G3mwClOJMi7NhmLffvVsAzJPRsowWd1zWOmexOqPiGBk4oQlRKORUP1BzoecM0aZCv1x1usegyOlQvGjD7sMtSN/akPaKNiMGK1c/sv5VaiHR7DyT1c7tUeWTru+Qy5aPdnTMSWD5yl6yjJ0JKsDqrMIFQ8L/crFeQwx3RuLlLlS0mVSbga5JZLWQ55ybbredwENct4N0fJ3vrxdza4ojMxF7BChLvsWcI90cyPCY76Gu6qxlVcnQjXzxjC6dUdFurcPGeH3FRxDH1O9OXoo3gQxdtvJ8QkW5Krea/CJ/FalHnX2Ik6GPBZaKhdntHedDIamakav5tvJoUhJ8ksMgXin+b6h7a224CPrwACnvEwNMtldBQbCBziMLzz4BbpgNX4NM98vaE1exW6HT1PCuWlfHry+pyc9vRRtmkQsCv37d4M/lTr55XB3ESw5gkqnBKhGlw4roGq2rXRc=
  - secure: dgjqyIkMRWg92RI51l2fpqynaMGJ7JlWJswZE+tiZVLlIL+CeHbrwwcIkxBR40aFii+lm/qWbYcuoPoWKiqzdKQ2Wp6H+f/Tg1F57jELU3BK8W5HjqSovkHioItyBchm24PB1upKxf4MutzcZVS4fTAz6hzr0ts012BstbbPd6Ni8BmOT47lg9dBk0yPflh/SBj1/3bs0SKj+rqhhQMNUS6DI1TAxLdySEVMGISVcTiRVGtsQ3IS9fyRKtyRYCBD7LCT57ZrIZr+LIixJhsfA4lgpHBL7LOB1Y6dR1pV0gjnQcyk/sN7gAy7HjPnZH5yv5avjkOrq85+rhnRg8mLAN7ar1+NbwZDukO85aOwwSMEMErCdLFTafXIMWGhnQ8FNXUGkVwEP2giyPcc/B9CF3l0N381TiwLesdKaVpd2ouQefkVUqByxhBHP1whAGmu7r3LCQ4uOcdr2csMbgU6eHpjEAccSj1UfIaYrC1ti5qlPxM2u+C7tq1m0SUdSoo+woqjQxaAQ4Efyagwvey0JIC/E8r6WKyxJseFR6DFYRH1DbgQTa/OrW82jVEn32zCmh3Qbd5ikqU9b1rDIYFupQiL/2KLZ3I9pGQZAVrsr9OCrH4/dPxCfGAZ1CPIcJwm68yGnnvpNVrlu/OIDrTXWfLiZWTwTZwPHVtmHqdY3X4=